<template>
    <div>
        <Row type="flex" justify="space-around">
            <Col :span="22">
            <div v-if="!currentPath" class="path-setup">
                <Panel shadow>
                    <div slot="title">
                        <Icon type="md-school" />
                        AI Learning Path Generator
                    </div>
                    <div class="setup-content">

                        <div class="online-learning-entry">
                            <h3>想要更个性化的题目推荐？</h3>
                            <p>我们的在线学习系统会根据您的实时反馈不断优化推荐算法</p>
                            <Button type="primary" @click="goToOnlineLearningRecommendation">
                                <Icon type="md-rocket" /> 尝试在线学习推荐
                            </Button>
                        </div>

                        <Form :model="pathConfig" :label-width="140" ref="pathConfigForm">
                            <FormItem label="Learning Goal">
                                <Select v-model="pathConfig.goal" placeholder="Select your learning goal">
                                    <Option value="general">General Programming</Option>
                                    <Option value="interview">Technical Interview</Option>
                                    <Option value="algorithm">Algorithm Competition</Option>
                                    <Option value="data_science">Data Science</Option>
                                    <Option value="web_development">Web Development</Option>
                                    <Option value="mobile_development">Mobile Development</Option>
                                </Select>
                                <p class="form-desc">What do you want to achieve with this learning path?</p>
                            </FormItem>

                            <FormItem label="Current Level">
                                <Select v-model="pathConfig.level" placeholder="Select your current level">
                                    <Option value="beginner">Beginner</Option>
                                    <Option value="intermediate">Intermediate</Option>
                                    <Option value="advanced">Advanced</Option>
                                </Select>
                                <p class="form-desc">If not selected, system will automatically assess your level</p>
                            </FormItem>

                            <FormItem label="Focus Areas">
                                <CheckboxGroup v-model="pathConfig.focusAreas">
                                    <Checkbox label="algorithms">Algorithms</Checkbox>
                                    <Checkbox label="data_structures">Data Structures</Checkbox>
                                    <Checkbox label="system_design">System Design</Checkbox>
                                    <Checkbox label="debugging">Debugging</Checkbox>
                                </CheckboxGroup>
                                <p class="form-desc">Select specific areas you want to focus on (optional)</p>
                            </FormItem>

                            <FormItem>
                                <Button type="primary" @click="generatePath" :loading="generating" size="large" long>
                                    <Icon type="md-rocket" /> Generate My Learning Path
                                </Button>
                            </FormItem>
                        </Form>

                        <div v-if="recentPaths.length > 0" class="recent-paths">
                            <h3>Recent Learning Paths</h3>
                            <div v-for="path in recentPaths" :key="path.id" class="recent-path-item">
                                <div class="path-info">
                                    <h4>{{ path.title }}</h4>
                                    <p>{{ path.description }}</p>
                                    <p class="path-meta">
                                        <span>
                                            <Icon type="md-time" /> {{ path.estimated_duration }} hours
                                        </span>
                                        <span>
                                            <Icon type="md-calendar" /> {{ path.create_time | localtime }}
                                        </span>
                                    </p>
                                </div>
                                <Button @click="loadPath(path.id)" size="small">Continue</Button>
                            </div>
                        </div>

                        <div class="learning-path-info">
                            <h3>About Learning Paths</h3>
                            <p>Learning paths are personalized roadmaps generated by our AI to help you achieve your
                                programming goals.
                                Each path is tailored to your current skill level and learning objectives.</p>
                            <div class="features">
                                <Row :gutter="20">
                                    <Col span="8">
                                    <div class="feature-card">
                                        <Icon type="md-person" size="30" color="#2d8cf0" />
                                        <h4>Personalized</h4>
                                        <p>Customized to your skill level and goals</p>
                                    </div>
                                    </Col>
                                    <Col span="8">
                                    <div class="feature-card">
                                        <Icon type="md-sync" size="30" color="#19be6b" />
                                        <h4>Adaptive</h4>
                                        <p>Adjusts based on your progress and feedback</p>
                                    </div>
                                    </Col>
                                    <Col span="8">
                                    <div class="feature-card">
                                        <Icon type="md-checkmark-circle" size="30" color="#ff9900" />
                                        <h4>Comprehensive</h4>
                                        <p>Covers concepts, problems, and projects</p>
                                    </div>
                                    </Col>
                                </Row>
                            </div>
                        </div>
                    </div>
                </Panel>
            </div>

            <div v-else class="path-detail">
                <Panel shadow>
                    <div slot="title" class="path-header">
                        <div>
                            <Icon type="md-map" />
                            {{ currentPath.title }}
                            <Tag color="blue">{{ currentPath.estimated_duration }} hours</Tag>
                        </div>
                        <div class="path-actions">
                            <Button @click="exportPath" size="small" style="margin-right: 10px;">
                                <Icon type="md-download" /> Export
                            </Button>
                            <Button @click="backToSetup" size="small">
                                <Icon type="md-arrow-back" /> Back
                            </Button>
                        </div>
                    </div>

                    <div class="path-description">
                        <p>{{ currentPath.description }}</p>
                    </div>

                    <div class="path-overview">
                        <Row :gutter="20">
                            <Col span="8">
                            <Card class="overview-card">
                                <div class="overview-item">
                                    <Icon type="md-list" size="24" color="#2d8cf0" />
                                    <div class="overview-text">
                                        <div class="overview-number">{{ totalNodes }}</div>
                                        <div class="overview-label">Steps</div>
                                    </div>
                                </div>
                            </Card>
                            </Col>
                            <Col span="8">
                            <Card class="overview-card">
                                <div class="overview-item">
                                    <Icon type="md-time" size="24" color="#ff9900" />
                                    <div class="overview-text">
                                        <div class="overview-number">{{ currentPath.estimated_duration }}</div>
                                        <div class="overview-label">Hours</div>
                                    </div>
                                </div>
                            </Card>
                            </Col>
                            <Col span="8">
                            <Card class="overview-card">
                                <div class="overview-item">
                                    <Icon type="md-trophy" size="24" color="#19be6b" />
                                    <div class="overview-text">
                                        <div class="overview-number">{{ completedNodes }}</div>
                                        <div class="overview-label">Completed</div>
                                    </div>
                                </div>
                            </Card>
                            </Col>
                        </Row>
                    </div>

                    <div class="path-progress">
                        <div class="progress-info">
                            <span>Your Progress</span>
                            <span>{{ completedNodes }} / {{ totalNodes }} completed</span>
                        </div>
                        <Progress :percent="progressPercent" :status="progressPercent === 100 ? 'success' : 'active'" />
                    </div>

                    <div class="path-nodes">
                        <Timeline>
                            <TimelineItem v-for="(node, index) in pathNodes" :key="node.id"
                                :color="getNodeStatusColor(node.status)">
                                <div class="node-item" :class="{ 'current-node': currentNodeIndex === index }">
                                    <div class="node-header">
                                        <Icon :type="getNodeTypeIcon(node.node_type)" />
                                        <strong>{{ node.title }}</strong>
                                        <Tag :color="getNodeTypeColor(node.node_type)">
                                            {{ getNodeTypeName(node.node_type) }}
                                        </Tag>
                                        <span class="node-time">{{ node.estimated_time }} min</span>
                                    </div>

                                    <div class="node-description">
                                        <p>{{ node.description }}</p>
                                        <div v-if="node.knowledge_point" class="knowledge-point-info">
                                            <Icon type="md-compass" /> 关联知识点:
                                            <Tag color="primary">{{ node.knowledge_point }}</Tag>
                                        </div>
                                    </div>
                                    <div class="node-time-info" v-if="node.start_time || node.completion_time">
                                        <div v-if="node.start_time" class="start-time">
                                            <Icon type="md-time" /> 开始时间: {{ new Date(node.start_time).toLocaleString()
                                            }}
                                        </div>
                                        <div v-if="node.completion_time" class="completion-time">
                                            <Icon type="md-checkmark-circle" /> 完成时间: {{ new
                                                Date(node.completion_time).toLocaleString() }}
                                        </div>
                                    </div>


                                    <div v-if="node.prerequisites && node.prerequisites.length"
                                        class="node-prerequisites">
                                        <strong>Prerequisites:</strong>
                                        <Tag v-for="(prereq, idx) in node.prerequisites" :key="idx" color="default">
                                            {{ prereq }}
                                        </Tag>
                                    </div>

                                    <div class="node-resources" v-if="node.resources && node.resources.length">
                                        <strong>Resources:</strong>
                                        <div class="resource-list">
                                            <a v-for="(resource, idx) in node.resources" :key="idx" :href="resource.url"
                                                target="_blank" class="resource-link">
                                                <Icon type="md-link" /> {{ resource.title }}
                                            </a>
                                        </div>
                                    </div>

                                    <div class="node-actions">
                                        <Button v-if="node.knowledge_point_id" size="small"
                                            @click="goToKnowledgePoint(node.knowledge_point_id)"
                                            style="margin-left: 10px;">
                                            <Icon type="md-compass" /> 查看知识点详情
                                        </Button>
                                        <Button v-if="node.node_type === 'problem'" size="small"
                                            @click="goToProblem(node.content_id)"
                                            :disabled="node.status === 'completed' && currentNodeIndex !== index">
                                            <Icon type="md-code" /> Solve Problem
                                        </Button>

                                        <Button v-if="node.node_type === 'concept'" size="small"
                                            @click="goToConcept(node.content_id)"
                                            :disabled="node.status === 'completed' && currentNodeIndex !== index">
                                            <Icon type="md-book" /> Learn Concept
                                        </Button>

                                        <Button v-if="node.node_type === 'project'" size="small"
                                            @click="goToProject(node.content_id)"
                                            :disabled="node.status === 'completed' && currentNodeIndex !== index">
                                            <Icon type="md-construct" /> View Project
                                        </Button>

                                        <Button v-if="node.status === 'pending'" type="primary" size="small"
                                            @click="startNode(node.id, index)" :loading="completingNode === node.id">
                                            <Icon type="md-play" /> 开始学习
                                        </Button>

                                        <Button v-if="node.status !== 'completed'" type="success" size="small"
                                            @click="completeNode(node.id, index)" :loading="completingNode === node.id">
                                            <Icon type="md-checkmark" /> Mark as Completed
                                        </Button>

                                        <Button v-else type="success" size="small" disabled>
                                            <Icon type="md-checkmark-circle" /> Completed
                                        </Button>

                                        <Button v-if="currentNodeIndex !== index" size="small"
                                            @click="setCurrentNode(index)">
                                            <Icon type="md-eye" /> View Details
                                        </Button>
                                    </div>
                                </div>
                            </TimelineItem>
                        </Timeline>
                    </div>

                    <div class="path-feedback" v-if="currentPath">
                        <h3>How was this learning path?</h3>
                        <p>Help us improve by providing feedback on your experience.</p>
                        <Rate v-model="pathRating" />
                        <Button type="primary" @click="submitFeedback" :loading="feedbackLoading"
                            style="margin-top: 10px;">
                            Submit Feedback
                        </Button>
                    </div>
                </Panel>
            </div>
            </Col>
        </Row>
    </div>
</template>
<script>
import api from '@oj/api'
import { mapGetters } from 'vuex'
import Panel from '@oj/components/Panel.vue'

export default {
    name: 'LearningPath',
    components: {
        Panel
    },
    data() {
        return {
            pathConfig: {
                goal: 'general',
                level: '',
                focusAreas: []
            },
            generating: false,
            currentPath: null,
            pathNodes: [],
            currentNodeIndex: 0,
            recentPaths: [],
            completingNode: null,
            pathRating: 0,
            feedbackLoading: false

        }
    },
    computed: {
        ...mapGetters(['user']),
        totalNodes() {
            return this.pathNodes.length
        },
        completedNodes() {
            return this.pathNodes.filter(node => node.status === 'completed').length
        },
        progressPercent() {
            if (this.totalNodes === 0) return 0
            return Math.round((this.completedNodes / this.totalNodes) * 100)
        }
    },
    mounted() {
        this.loadRecentPaths()
    },
    methods: {
        async generatePath() {
            this.generating = true
            try {
                // Prepare the data to send to the API
                const requestData = {
                    goal: this.pathConfig.goal,
                    level: this.pathConfig.level || null
                };

                // Only add focus_areas if there are selected areas
                if (this.pathConfig.focusAreas && this.pathConfig.focusAreas.length > 0) {
                    requestData.focus_areas = this.pathConfig.focusAreas;
                }

                const res = await api.generateLearningPath(requestData);
                this.currentPath = res.data.data;
                this.pathNodes = this.currentPath.nodes || [];
                this.currentNodeIndex = 0;
                this.$success('Learning path generated successfully!');
            } catch (err) {
                this.$error(err.message || 'Failed to generate learning path');
            } finally {
                this.generating = false;
            }
        },

        goToProblem(problemId) {
            if (problemId) {
                this.$router.push({ name: 'problem-details', params: { problemID: problemId } });
            } else {
                this.$Message.warning('Problem not available');
            }
        },
        goToOnlineLearningRecommendation() {
            this.$router.push({ name: 'online-learning-recommendation' });
        },


        goToConcept(conceptId) {
            if (conceptId) {
                // For now, just show a message. In a real implementation, this would navigate to a concept page
                this.$Message.info('Concept viewing is not implemented yet');
            } else {
                this.$Message.warning('Concept not available');
            }
        },

        goToProject(projectId) {
            if (projectId) {
                // For now, just show a message. In a real implementation, this would navigate to a project page
                this.$Message.info('Project viewing is not implemented yet');
            } else {
                this.$Message.warning('Project not available');
            }
        },

        exportPath() {
            // Create a blob with the path data
            const pathData = {
                title: this.currentPath.title,
                description: this.currentPath.description,
                estimated_duration: this.currentPath.estimated_duration,
                nodes: this.pathNodes,
                generated_at: new Date().toISOString()
            };

            const blob = new Blob([JSON.stringify(pathData, null, 2)], {
                type: 'application/json'
            });

            // Create download link
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `learning-path-${this.currentPath.id}.json`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);

            this.$Message.success('Learning path exported successfully!');
        },

        async loadRecentPaths() {
            try {
                const res = await api.getLearningPaths();
                this.recentPaths = res.data.data.slice(0, 3); // 只显示最近3个
            } catch (err) {
                // 静默处理，不影响主功能
            }
        },

        async submitFeedback() {
            if (this.pathRating === 0) {
                this.$Message.warning('Please provide a rating');
                return;
            }

            this.feedbackLoading = true;
            try {
                // In a real implementation, this would call an API endpoint
                await new Promise(resolve => setTimeout(resolve, 1000)); // Simulate API call
                this.$Message.success('Thank you for your feedback!');
                this.pathRating = 0;
            } catch (err) {
                this.$Message.error('Failed to submit feedback');
            } finally {
                this.feedbackLoading = false;
            }
        },

        async loadPath(pathId) {
            try {
                const res = await api.getLearningPathDetail(pathId);
                this.currentPath = res.data.data;

                // 正确处理节点数据
                if (res.data.data && res.data.data.nodes) {
                    this.pathNodes = res.data.data.nodes;
                } else {
                    this.pathNodes = [];
                }

                this.currentNodeIndex = 0;
            } catch (err) {
                console.error('Failed to load learning path:', err);
                this.$error('Failed to load learning path: ' + (err.message || 'Unknown error'));
            }
        },

        backToSetup() {
            this.currentPath = null;
            this.pathNodes = [];
            this.loadRecentPaths();
        },

        setCurrentNode(index) {
            this.currentNodeIndex = index;
        },

        async completeNode(nodeId, index) {
            await this.updateNodeStatus(nodeId, 'completed', index);
        },
        async startNode(nodeId, index) {
            await this.updateNodeStatus(nodeId, 'in_progress', index);
        },

        getNodeStatusColor(status) {
            switch (status) {
                case 'completed': return 'green';
                case 'in_progress': return 'blue';
                default: return 'gray';
            }
        },

        getNodeTypeIcon(type) {
            switch (type) {
                case 'problem': return 'md-code';
                case 'concept': return 'md-book';
                case 'project': return 'md-construct';
                default: return 'md-document';
            }
        },

        getNodeTypeColor(type) {
            switch (type) {
                case 'problem': return 'primary';
                case 'concept': return 'success';
                case 'project': return 'warning';
                default: return 'default';
            }
        },

        getNodeTypeName(type) {
            switch (type) {
                case 'problem': return 'Problem';
                case 'concept': return 'Concept';
                case 'project': return 'Project';
                default: return 'Item';
            }
        },
        goToKnowledgePoint(knowledgePointId) {
            if (knowledgePointId) {
                this.$router.push({ name: 'knowledge-points', query: { id: knowledgePointId } });
            } else {
                this.$Message.warning('知识点信息不可用');
            }
        },
        async updateNodeStatus(nodeId, status, index) {
            this.completingNode = nodeId;
            try {
                const res = await api.updateLearningPathNode(nodeId, { status: status });
                // 更新本地状态，包括新添加的时间字段
                this.$set(this.pathNodes[index], 'status', status);
                if (res.data.data) {
                    if (res.data.data.start_time) {
                        this.$set(this.pathNodes[index], 'start_time', res.data.data.start_time);
                    }
                    if (res.data.data.completion_time) {
                        this.$set(this.pathNodes[index], 'completion_time', res.data.data.completion_time);
                    }
                }

                if (status === 'completed') {
                    this.$Message.success('节点已标记为完成!');

                    // 如果不是最后一个节点，自动跳转到下一个
                    if (index < this.pathNodes.length - 1) {
                        this.currentNodeIndex = index + 1;
                    }
                } else if (status === 'in_progress') {
                    this.$Message.success('节点已标记为进行中!');
                } else {
                    this.$Message.success('节点状态已更新!');
                }
            } catch (err) {
                this.$Message.error('更新节点状态失败');
            } finally {
                this.completingNode = null;
            }
        },

    }
}
</script>
<style lang="less" scoped>
.setup-content {
    padding: 20px 0;

    .form-desc {
        font-size: 12px;
        color: #808695;
        margin-top: 5px;
        margin-bottom: 0;
    }

    .recent-paths {
        margin-top: 30px;
        padding-top: 20px;
        border-top: 1px solid #e8eaec;

        h3 {
            margin-bottom: 15px;
        }

        .recent-path-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 15px;
            border: 1px solid #e8eaec;
            border-radius: 4px;
            margin-bottom: 10px;

            .path-info {
                flex: 1;

                h4 {
                    margin: 0 0 5px 0;
                }

                p {
                    margin: 5px 0;
                    font-size: 13px;
                    color: #657180;
                }

                .path-meta {
                    display: flex;
                    gap: 15px;
                    font-size: 12px;
                    color: #808695;
                }
            }
        }
    }

    .learning-path-info {
        margin-top: 40px;
        padding-top: 20px;
        border-top: 1px solid #e8eaec;

        h3 {
            text-align: center;
            margin-bottom: 20px;
        }

        p {
            text-align: center;
            margin-bottom: 30px;
            color: #657180;
        }

        .features {
            .feature-card {
                text-align: center;
                padding: 20px 10px;

                h4 {
                    margin: 15px 0 10px;
                }

                p {
                    margin: 0;
                    font-size: 13px;
                    color: #808695;
                }
            }
        }
    }
}

.online-learning-entry {
    background-color: #f0f8ff;
    border: 1px solid #2d8cf0;
    border-radius: 4px;
    padding: 15px;
    margin-bottom: 20px;

    h3 {
        margin-top: 0;
        color: #2d8cf0;
    }

    p {
        color: #657180;
        margin-bottom: 15px;
    }
}

.path-detail {
    .path-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .path-description {
        margin: 15px 0;
        padding: 15px;
        background-color: #f8f9fa;
        border-radius: 4px;
    }

    .path-overview {
        margin: 20px 0;

        .overview-card {
            text-align: center;
            border: 1px solid #e8eaec;

            .overview-item {
                display: flex;
                align-items: center;
                justify-content: center;

                .overview-text {
                    margin-left: 10px;

                    .overview-number {
                        font-size: 24px;
                        font-weight: bold;
                        color: #2d8cf0;
                    }

                    .overview-label {
                        font-size: 12px;
                        color: #808695;
                    }
                }
            }
        }
    }

    .path-progress {
        margin: 20px 0;

        .progress-info {
            display: flex;
            justify-content: space-between;
            margin-bottom: 8px;
            font-size: 14px;
        }
    }

    .node-item {
        padding: 15px;
        border-radius: 4px;
        transition: all 0.3s;

        &.current-node {
            background-color: #e6f7ff;
            border: 1px solid #91d5ff;
        }

        .node-header {
            display: flex;
            align-items: center;
            gap: 10px;
            margin-bottom: 10px;

            strong {
                font-size: 16px;
            }

            .node-time {
                margin-left: auto;
                font-size: 12px;
                color: #808695;
            }
        }

        .node-description {
            margin: 10px 0;
            font-size: 14px;
            color: #657180;
        }

        .knowledge-point-info {
            margin-top: 10px;
            padding: 8px 12px;
            background-color: #f0faff;
            border-radius: 4px;
            border-left: 3px solid #2d8cf0;
        }


        .node-prerequisites {
            margin: 10px 0;
            font-size: 13px;

            strong {
                margin-right: 10px;
            }
        }

        .node-resources {
            margin: 10px 0;
            font-size: 13px;

            strong {
                display: block;
                margin-bottom: 5px;
            }

            .resource-list {
                .resource-link {
                    display: block;
                    margin: 3px 0;
                    color: #2d8cf0;
                    text-decoration: underline;

                    &:hover {
                        color: #5cadff;
                    }
                }
            }
        }

        .node-actions {
            margin-top: 15px;
            display: flex;
            gap: 10px;
            flex-wrap: wrap;
        }
    }

    .path-feedback {
        margin-top: 30px;
        padding-top: 20px;
        border-top: 1px solid #e8eaec;
        text-align: center;

        h3 {
            margin-bottom: 10px;
        }

        p {
            margin-bottom: 15px;
            color: #657180;
        }
    }
}

.node-time-info {
    margin-top: 10px;
    padding: 8px 12px;
    background-color: #f6ffed;
    border-radius: 4px;
    border-left: 3px solid #52c41a;

    div {
        margin: 5px 0;
        font-size: 13px;
        color: #52c41a;
    }

    .completion-time {
        color: #138913;
        font-weight: bold;
    }
}
</style>