# Generated by Django 3.2.25 on 2025-10-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignmentstatistics_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='max_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
