services:
  # Redis服务
  oj-redis:
    image: redis:6-alpine
    restart: always
    container_name: oj-redis-dev
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - oj-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  # PostgreSQL数据库
  oj-postgres:
    image: postgres:13-alpine
    restart: always
    container_name: oj-postgres-dev
    ports:
      - "5435:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
    networks:
      - oj-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # 判题服务器
  oj-judge:
    build:
      context: ../JudgeServer
      dockerfile: Dockerfile
    image: oj/judge_server:dev
    restart: always
    container_name: oj-judge-dev
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/log:/log
      - ./data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://oj-judge-dev:8080
      - BACKEND_URL=http://oj-backend-dev:8000/api/judge_server_heartbeat/
      - TOKEN=CHANGE_THIS_DEV_TOKEN
    networks:
      - oj-network
    ports:
      - "12358:8080"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # 后端开发服务
  oj-backend:
    build:
      context: ../OnlineJudge
      dockerfile: Dockerfile.dev
    image: oj/backend:dev
    container_name: oj-backend-dev
    depends_on:
      - oj-redis
      - oj-postgres
    volumes:
      - ../OnlineJudge:/app
      - ./data/backend:/data
    environment:
      - POSTGRES_HOST=oj-postgres-dev
      - POSTGRES_PORT=5432
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
      - REDIS_HOST=oj-redis-dev
      - REDIS_PORT=6379
      - JUDGE_SERVER_TOKEN=CHANGE_THIS_DEV_TOKEN
    ports:
      - "8000:8000"
    networks:
      - oj-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # 前端开发服务
  oj-frontend:
    build:
      context: ../OnlineJudgeFE
      dockerfile: Dockerfile.dev
    image: oj/frontend:dev
    container_name: oj-frontend-dev
    volumes:
      - ../OnlineJudgeFE:/OJ_FE
      - /OJ_FE/node_modules
    environment:
      - TARGET=http://oj-backend-dev:8000
      - PORT=8081
    ports:
      - "8081:8081"
    dns:
      - 202.114.96.1
      - 8.8.8.8 # 备用：Google 公共 DNS
    networks:
      - oj-network
    depends_on:
      - oj-backend
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

# 网络定义
networks:
  oj-network:
    driver: bridge
