# Generated by Django 3.2.25 on 2025-10-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_auto_20251018_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='description_complexity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='problem',
            name='description_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='problem',
            name='description_sentence_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='description_word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='last_nlp_analysis_time',
            field=models.DateTimeField(null=True),
        ),
    ]
