# Generated by Django 3.2.25 on 2025-10-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_aiconversation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconversation',
            name='title',
            field=models.TextField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
