# Generated by Django 3.2.25 on 2025-10-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_airecommendation_airecommendationfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICodeExplanationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.TextField(unique=True)),
                ('language', models.TextField()),
                ('explanation', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'ai_code_explanation_cache',
            },
        ),
        migrations.AddIndex(
            model_name='aicodeexplanationcache',
            index=models.Index(fields=['code_hash'], name='ai_code_exp_code_ha_17e3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='aicodeexplanationcache',
            index=models.Index(fields=['create_time'], name='ai_code_exp_create__f4d2ae_idx'),
        ),
    ]
