# Generated by Django 3.2.25 on 2025-10-21 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0005_auto_20251020_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUserLearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('estimated_duration', models.IntegerField(help_text='预计完成时间(小时)')),
                ('path_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_user_learning_path',
            },
        ),
        migrations.CreateModel(
            name='AIUserLearningPathNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.TextField(help_text='节点类型: concept, problem, project')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('content_id', models.IntegerField(help_text='关联的内容ID(如题目ID、概念ID等)')),
                ('order', models.IntegerField()),
                ('estimated_time', models.IntegerField(help_text='预计完成时间(分钟)')),
                ('prerequisites', models.JSONField(default=list, help_text='前置知识点')),
                ('status', models.TextField(default='pending', help_text='状态: pending, in_progress, completed')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.aiuserlearningpath')),
            ],
            options={
                'db_table': 'ai_user_learning_path_node',
            },
        ),
        migrations.CreateModel(
            name='AIUserKnowledgeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_point', models.TextField(help_text='知识点名称')),
                ('proficiency_level', models.FloatField(default=0.0, help_text='掌握程度(0-1)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_user_knowledge_state',
                'unique_together': {('user', 'knowledge_point')},
            },
        ),
    ]
