# Generated by Django 3.2.25 on 2025-10-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_auto_20251018_1001'),
        ('ai', '0006_aiuserknowledgestate_aiuserlearningpath_aiuserlearningpathnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='知识点名称', unique=True)),
                ('description', models.TextField(help_text='知识点描述')),
                ('category', models.TextField(help_text='知识点分类')),
                ('difficulty', models.IntegerField(help_text='难度等级(1-5)')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('parent_points', models.ManyToManyField(blank=True, help_text='前置知识点', to='ai.KnowledgePoint')),
                ('related_problems', models.ManyToManyField(blank=True, help_text='相关题目', to='problem.Problem')),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
                'db_table': 'ai_knowledge_point',
            },
        ),
    ]
