# Generated by Django 3.2.25 on 2025-10-22 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_knowledgepoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.TextField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('openkey', 'OpenKey'), ('deepseek', 'DeepSeek')]),
        ),
        migrations.AlterField(
            model_name='aiuserknowledgestate',
            name='knowledge_point',
            field=models.ForeignKey(help_text='知识点', on_delete=django.db.models.deletion.CASCADE, to='ai.knowledgepoint'),
        ),
    ]
