# Generated by Django 3.2.25 on 2025-10-22 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_auto_20251022_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiuserlearningpathnode',
            name='knowledge_point',
            field=models.ForeignKey(blank=True, help_text='关联的知识点', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.knowledgepoint'),
        ),
    ]
