# Generated by Django 3.2.25 on 2025-10-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_aiuserlearningpathnode_knowledge_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepoint',
            name='weight',
            field=models.FloatField(default=1.0, help_text='推荐权重'),
        ),
    ]
