# Generated by Django 3.2.25 on 2025-10-24 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0010_knowledgepoint_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAbilityDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField()),
                ('weight', models.FloatField(default=1.0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_ability_dimension',
            },
        ),
        migrations.CreateModel(
            name='AIUserAbilityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('proficiency_level', models.TextField(default='beginner')),
                ('evidence', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.aiabilitydimension')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_user_ability_detail',
                'unique_together': {('user', 'dimension')},
            },
        ),
        migrations.CreateModel(
            name='AIProgrammingAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0)),
                ('basic_programming_score', models.FloatField(default=0.0)),
                ('data_structure_score', models.FloatField(default=0.0)),
                ('algorithm_design_score', models.FloatField(default=0.0)),
                ('problem_solving_score', models.FloatField(default=0.0)),
                ('level', models.TextField(choices=[('beginner', '入门'), ('intermediate', '中级'), ('advanced', '高级'), ('expert', '专家')], default='beginner')),
                ('analysis_report', models.JSONField(default=dict)),
                ('last_assessed', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_programming_ability',
                'unique_together': {('user',)},
            },
        ),
    ]
