# Generated by Django 3.2.25 on 2025-10-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_aiabilitydimension_aiprogrammingability_aiuserabilitydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='api_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.TextField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('openkey', 'OpenKey'), ('deepseek', 'DeepSeek'), ('ollama', 'Ollama')]),
        ),
    ]
