# Generated by Django 3.2.25 on 2025-10-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_auto_20251027_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepoint',
            name='embedding',
            field=models.TextField(blank=True, help_text='知识点的向量表示'),
        ),
        migrations.AddField(
            model_name='knowledgepoint',
            name='frequency',
            field=models.IntegerField(default=0, help_text='知识点在题目中出现的频率'),
        ),
        migrations.AddField(
            model_name='knowledgepoint',
            name='importance',
            field=models.FloatField(default=1.0, help_text='知识点重要性'),
        ),
    ]
