# Generated by Django 3.2.25 on 2025-11-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0013_auto_20251030_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiuserlearningpathnode',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='aiuserabilitydetail',
            name='improvement_rate',
            field=models.FloatField(default=0.0, help_text='能力提升速率'),
        ),
        migrations.AddField(
            model_name='aiuserlearningpathnode',
            name='completion_time',
            field=models.DateTimeField(blank=True, help_text='完成时间', null=True),
        ),
        migrations.AddField(
            model_name='aiuserlearningpathnode',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='开始时间', null=True),
        ),
    ]
