# Generated by Django 3.2.25 on 2025-11-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0015_aiuserabilityhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendation',
            name='algorithm_used',
            field=models.CharField(default='hybrid', max_length=50),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='recommendation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
