# Generated by Django 3.2.25 on 2025-11-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0016_auto_20251103_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airecommendation',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
